#!/bin/bash
figlet F@ACE00K
echo "masukan username"
read p
echo "masukan id"
read q
$proses hack berjalan
443rebcueyayrfutrygrrfhdf
echo "hack berhasil"
read p
echo "tekan [E]xit/[A]gain
reaad q
figlet 201_TOOL
